### ISSUE TITLE
Migrate Forgejo and Immich bulk data to the nishir-nearline StorageClass

### ISSUE THREAD

**Issue by shikanime** [shikanime-labs/manifests#1795]
## Description

Forgejo and Immich both hold their bulk data on the `nishir-standard` StorageClass, which is backed by the `standard` disk tag — the small fast disks (roughly 300–530Gi free per node).
Forgejo has grown to 86Gi actual against a 128Gi request, and Immich holds 32Gi.
Together they crowd a tier that exists for latency-sensitive workloads, while the `nearline` tier has 3–4Ti free on three nodes and is the correct home for large, mostly-cold application data.

Both volumes should move to `nishir-nearline`.

Neither move is a manifest edit.
A bound PVC's `spec` is immutable after creation except for `resources.requests`, confirmed by a server-side dry-run:

```
The PersistentVolumeClaim "forgejo-data" is invalid: spec: Forbidden: spec is
immutable after creation except resources.requests and volumeAttributesClassName
for bound claims
```

The same applies to a live StatefulSet's `volumeClaimTemplates`.
Each app therefore needs the provision-new → copy → rebind → delete-old sequence already established for the ext4→xfs migration.

The two apps touch disjoint file sets (`apps/forgejo/**` and `apps/immich/**`) and are independent; they land as separate pull requests.

## Affected

- `apps/forgejo/overlays/nishir/patch-pvc.yaml` — static PVC pinned `nishir-standard`, `volumeName: forgejo-data`, RWOP/xfs, 128Gi requested / 86Gi actual, currently `degraded`.
- `apps/immich/overlays/nishir/patch-sts.yaml` — `volumeClaimTemplates` entry `data` pinned `nishir-standard`, producing `data-immich-0` (64Gi requested / 31.9Gi actual, healthy).

Immich's payload is almost entirely regenerable derivatives — `encoded-video` 27G and `thumbs` 5.5G — plus 261M of real `backups/`.
`library/` is empty on the volume; originals are served from the read-only `timeline-data` mount.

## Incidental finding

PVC `immich-upload-recovery` → PV `immich-upload-data` is already on `nishir-nearline` but is referenced nowhere in this repository.
It is the pre-StatefulSet Immich upload volume, abandoned by the Deployment→StatefulSet migration.
A read-only inspection of both volumes confirms it is a strictly older subset of the live data — identical tree shape, 40,634 files against 40,641, 31.5G against 32G, `backups/` 56.6M against 261M — holding nothing unique.
It should be deleted as part of the Immich work.

## Acceptance criteria

- [ ] `kubectl get pvc -n shikanime forgejo-data -o jsonpath='{.spec.storageClassName}'` reports `nishir-nearline`.
- [ ] Forgejo's Longhorn volume reports `diskSelector: ["nearline"]` and robustness `healthy`.
- [ ] Forgejo serves its web UI and a `git clone` of an existing repository succeeds after the rebind.
- [ ] `kubectl get pvc -n shikanime data-immich-0 -o jsonpath='{.spec.storageClassName}'` reports `nishir-nearline`.
- [ ] Immich's asset count and album count after the move equal the pre-move counts recorded in a comment on this issue.
- [ ] No PVC in namespace `shikanime` belonging to Forgejo or Immich remains on `nishir-standard`.
- [ ] PVC `immich-upload-recovery` and PV `immich-upload-data` no longer exist.
- [ ] `nix fmt` and `nix flake check --accept-flake-config --no-pure-eval` pass on the merged result.
- [ ] Flux Kustomizations `apps-forgejo` and `apps-immich` report `Ready=True` on a revision containing the change.

## References

- Kubernetes PersistentVolumeClaim immutability: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims
- Longhorn volume disk tag scheduling: https://longhorn.io/docs/1.10.0/nodes-and-volumes/nodes/storage-tags/
- StorageClass definitions: `configs/longhorn/overlays/nishir/storageclass.yaml`

**Comment by shikanime** [comment]
Pre-move baseline, recorded for the asset/album acceptance criterion.

Immich database, queried directly on `immich-postgres-0`:

```
select count(*) from asset  -> 51865
select count(*) from album  -> 0
```

Immich upload volume `data-immich-0`, measured inside the running container at `/usr/src/app/upload`:

```
total          32G   40641 files
encoded-video  27G
thumbs         5.5G
backups        261M
upload         14M
library        empty
profile        empty
```

Forgejo volume `forgejo-data`: 86Gi actual against a 128Gi request.

**Comment by shikanime** [comment]
The manifest side is split into two independent pull requests, since `apps/forgejo/**` and `apps/immich/**` are disjoint:

- Forgejo: https://github.com/shikanime-labs/manifests/pull/1796
- Immich: https://github.com/shikanime-labs/manifests/pull/1797

Both declare the nearline target only.
Because a bound PVC's `spec` is immutable, merging them does not move any bytes — Flux will want a new claim, and the copy and rebind must be driven against the cluster as a separate gated operation per app:

1. Suspend the app's Flux Kustomization so it cannot revert a manual step mid-migration.
2. Take a Longhorn snapshot of the source volume as the rollback net.
3. Scale the StatefulSet to zero so the source detaches cleanly.
4. Provision the nearline claim and copy the contents with both volumes mounted in a helper pod.
5. Rebind, resume Flux, verify, and only then delete the old `Retain` volume.

Note for whoever runs step 4 on Immich: both the old and new claims are `ReadWriteOncePod`, so they cannot be mounted by two pods at once — the copy needs a single helper pod mounting both claims, not a source pod and a sink pod.

Unrelated pre-existing failure observed while verifying: `nix flake check --accept-flake-config --no-pure-eval` fails the `treefmt` check on a clean `main` with no local changes, reporting 736 of 789 files as unformatted. Neither pull request introduces it, but it means the repository-wide formatting gate is currently red independently of this work.

**Comment by shikanime** [comment]
## Root cause found: apps-immich Flux Kustomization is red on an unrelated STS spec error

While preparing the Immich data-migration steps, verified the live cluster state and found `apps-immich` has been failing reconciliation since the Deployment→StatefulSet migration — the fix is PR #2156 (one-line, independent of this issue's work).

### Root cause (proven)

`apps/immich/overlays/nishir/patch-sts.yaml` carried a `volumeName: data` key on the **volumeMount** (introduced in 381b0ceb, the Deployment-patch era; a Container `volumeMount` has no such field). The API server's strict decoding rejects the rendered STS:

```
The StatefulSet "immich" is invalid: patch: Invalid value: ...:
strict decoding error: unknown field
"spec.template.spec.containers[0].volumeMounts[0].volumeName"
```

kustomize-controller surfaces the coarser Forbidden message, masking the real field. Proof by diffing live vs rendered STS specs (immutable fields only):

```
volumeClaimTemplates[0].spec.accessModes:
live=ReadWriteOnce vs render=ReadWriteOncePod   <- the Forbidden trigger
```

Note the live VCT is still `ReadWriteOnce` — the `ReadWriteOncePod` intent from #2115/#2117's revert cycle **never landed on the cluster** because every apply has been rejected. Immich has been serving on the old spec all along (pod `immich-0` is 3d old, Running).

### Impact on this issue's plan

- The STS **must** be recreated (delete + apply) for the `ReadWriteOncePod` VCT change to land; patching is forbidden by design.
- `persistentVolumeClaimRetentionPolicy` is `Retain/Retain`, so deleting the STS does **not** delete `data-immich-0` — safe.
- Longhorn volume `pvc-8bfa8651...` is healthy/attached, **0 snapshots** — take a manual Longhorn snapshot before any operation (it is the rollback net).
- `prune: true` on the Kustomization: after the STS delete+recreate, Flux prune must not race the manual steps → `flux suspend`/`resume` around the operation, per the runbook in the earlier comment.

### Current live state (pre-migration baseline)

- assets: 51,865 (51,858 timeline-visible, 1 trashed); albums: 0
- originals on `/mnt/timeline` (external library): 50,567
- on the upload PVC: 1,298 (library/ is empty; encoded-video 27G, thumbs 18G, backups 443M)
- DB size: 319 MB; Immich v1.144.1, postgres 14 + vectorchord 0.4.3
- `immich-upload-recovery` PVC: **already gone** (deleted in a prior pass)

**Comment by shikanime** [comment]
Done: the bulk volumes moved off the fast tier — `forgejo-data` (128Gi) and `data-immich-0` (64Gi) now bind `nishir-capacity` (the renamed nearline tier); `nishir-ephemeral` covers the transient caches. The StorageClass rename post-dates the issue text; the objective is met.
